### PR TITLE
Modifies dates to ISO yyyy-mm-dd format + maintains consistent text encoding

### PR DESCRIPTION
**Pull request by shailshouryya**
This addresses
- [Issue 318](https://github.com/CSSEGISandData/COVID-19/issues/318)
- [Issue 319](https://github.com/CSSEGISandData/COVID-19/issues/319)
  - if we want to use a different encoding let me know, I will change this

### CODE REVIEW

**Comment by sethfischer** [comment]
The hyphen character "-" should be considered as a separator so as to conform with ISO_8601.

From https://en.wikipedia.org/wiki/ISO_8601

> The separator used between date values (year, month, week, and day) is the hyphen

For example `2020-03-09` being the 9th of March 2020.

This would allow the use of the same date format in file names as the "/" or "\\" characters are used as directory separators on many common operating systems.

For example on Windows, Mac, and Linux:

`2020-03-09.csv` is a valid file name.
`2020/03/09.csv` is not a valid file name.

**Comment by Shail-Shouryya** [comment]
I'll rename the files to follow `yyyy-mm-dd` as well.

I also looked through all the csv files and it looks like the files uploaded in the beginning used the `CRLF` extension and the files that have been uploaded in the past 2 weeks or so all use the `LF` extension. I'm thinking about changing the files that used the `CRLF` extension to use the `LF` extensions to maintain consistency with the format that's currently being used.

Is this okay, or is there anything else I should look at as well?

**Comment by sethfischer** [comment]
As you suggest I believe using LF would be best practice.

GitHub has a useful help page on the topic: https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

A `.gitattributes` could be added to the project as suggested in https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/ (which is referred to by the above GitHub help page).

```
*.csv    text
```

Thsi should tell git to automatically normalize *.csv files (convert CRLF to LF)

**Comment by Shail-Shouryya** [comment]
Comment on the merge: I accepted the incoming change on all 3 files, but it looks like the EOL encoding got switched back to `CRLF` even though the `.gitattributes` file had the conversion for all csv files to be encoded to `LF`.

**Comment by Shail-Shouryya** [comment]
Additional note: might be good to merge this in ASAP to avoid encoding issues conflicting with new data again :)

**Pull request closed without merging**
