### PR TITLE
update Peru cases

### PR DESCRIPTION
**Pull request by arankaren**
- https://peru21.pe/lima/minsa-confirma-seis-casos-de-coronavirus-en-lima-covid-19-noticia/
- https://web.archive.org/web/20200308023418/https://peru21.pe/lima/minsa-confirma-seis-casos-de-coronavirus-en-lima-covid-19-noticia/

### CODE REVIEW

**Comment by arankaren** [comment]
updated

**Comment by ZurMaD** [comment]
Hola @arankaren hemos abierto un [repositorio externo](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica) para el caso de américa latina.

**Comment by arankaren** [comment]
> Hola @arankaren hemos abierto un [repositorio externo](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica) para el caso de américa latina. No somos parte de CSSEGIS pero estamos centralizando la información en ese repositorio. Quizás pueda interesarte, estamos buscando maintainer por países.

@ZurMaD I'm not from Peru, I'm from China. However I know a very talented developer from his country https://www.hyperbola.info/members/security-team/#heckyel . His compatriot made a repository in codeberg https://codeberg.org/heckyel/notcovid19 with mirror in https://libregit.org/heckyel/notcovid19

**Comment by ZurMaD** [comment]
Thanks, we're going to try to contact him.

**Pull request closed without merging**
