### PR TITLE
Align France data with official source

### PR DESCRIPTION
**Pull request by Yqnn**
Official sources from French government:
- https://www.gouvernement.fr/info-coronavirus/carte-et-donnees
- https://github.com/opencovid19-fr/data/tree/master/ministere-sante

Fixes the followings issues (among others):
#1926
#2005
#2013
#2121   
#2134  
#2154  
#2173 
#2188 
#2202 
#2203

### CODE REVIEW

**Comment by Yqnn** [comment]
Updated with april, 16 data

**Comment by Yqnn** [comment]
Despite the 2 following commits, still a lot of errors in France data:
- https://github.com/CSSEGISandData/COVID-19/commit/75826dfd849184dca3fc2461f7c235bd32bf9f30
- https://github.com/CSSEGISandData/COVID-19/commit/c14991d73617e08479369e0fea8b067c5c4908e4


PR updated with april, 17 data

#2259 
#2246

**Comment by markfoodyburton** [comment]
Why are the numbers systematically wrong in the first place? Isn't this somehow automated?

**Comment by Yqnn** [comment]
> Why are the numbers systematically wrong in the first place? Isn't this somehow automated?

I guess it's automated, and the value taken is {confirmed_cases + suspected_cases} instead of {confirmed_cases}.
I will update my fork daily until they fix.

**Comment by Yqnn** [comment]
PR updated with april, 18 data

#2270

**Comment by markfoodyburton** [comment]
Thanks, makes sense.

**Comment by Yqnn** [comment]
PR updated with April 19 data

**Comment by traut21** [comment]
I'll jump in on this issue, although there are a dozen open issues concerning France - but where's he answer how to fix the problem?

From what I see 2020-03-15 was the last time when official numbers matched JHU.
Until 2020-04-11 the difference crawled at 1000 to 5000.
2020-04-12 happend a huge jump in numbers by 23 000 cases, leaving a gap of 40 000 for the last week - a difference of one third (122577 vs. 160292 for 2020-04-25)


What are you going to do about that? 
Just ignoring all those questions is no professional reaction.

**Pull request closed without merging**
