### PR TITLE
Add 3D earth (open source)

### PR DESCRIPTION
**Pull request by hugetiny**

### CODE REVIEW

**Comment by TylerCarberry** [comment]
Is this data accurate? The globe isn't showing any cases in North America. I wouldn't merge until it's getting real-time updates

**Comment by shemunkee** [comment]
The site sometimes goes down while they do maintenance and update numbers. 

> Is this data accurate? The globe isn't showing any cases in North America. I wouldn't merge until it's getting real-time updates

The site sometimes goes down while they do maintenance and update numbers. It's up now.

**Comment by TylerCarberry** [comment]
I was referring to @hugetiny's site at https://endof.world

**Comment by TylerCarberry** [comment]
Screen Shot 2020-03-09 at 2 49 38 PM

Nothing in north/south america

**Comment by hugetiny** [comment]
I fixed bugs caused by , between "" .
The visualization data is from
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv

Please check again

**Comment by Alexandros-Kordatzakis** [comment]
It would be nice to have a Pause/Play button somewhere on the screen so that I have the ability to disable the music... 
Also, a higher quality background would be much appreciated!

Thanks

**Comment by hugetiny** [comment]
I'm working on this

**Comment by hugetiny** [comment]
I disabled the bgm and replace a higher resolution jpg.
And It slows first time loading speed a little bit of course. 
I can't find a real && high resolution space picture in nasa.gov
Hope somebady could help me to replace a beautiful real space.

**Comment by hugetiny** [comment]
I found my new collaborator for my project.
This PR is shut down temporarily for further improvement

**Pull request closed without merging**
